/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as WwwImport } from './routes/_www'
import { Route as AppImport } from './routes/_app'
import { Route as WwwIndexImport } from './routes/_www/index'
import { Route as WwwLoginImport } from './routes/_www/login'
import { Route as WwwCreateAccountImport } from './routes/_www/create-account'
import { Route as Www404Import } from './routes/_www/404'
import { Route as AppHomeImport } from './routes/_app/home'
import { Route as WwwLegalIndexImport } from './routes/_www/legal/index'
import { Route as WwwHelpIndexImport } from './routes/_www/help/index'

// Create/Update Routes

const WwwRoute = WwwImport.update({
  id: '/_www',
  getParentRoute: () => rootRoute,
} as any)

const AppRoute = AppImport.update({
  id: '/_app',
  getParentRoute: () => rootRoute,
} as any)

const WwwIndexRoute = WwwIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WwwRoute,
} as any)

const WwwLoginRoute = WwwLoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => WwwRoute,
} as any)

const WwwCreateAccountRoute = WwwCreateAccountImport.update({
  id: '/create-account',
  path: '/create-account',
  getParentRoute: () => WwwRoute,
} as any)

const Www404Route = Www404Import.update({
  id: '/404',
  path: '/404',
  getParentRoute: () => WwwRoute,
} as any)

const AppHomeRoute = AppHomeImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AppRoute,
} as any)

const WwwLegalIndexRoute = WwwLegalIndexImport.update({
  id: '/legal/',
  path: '/legal/',
  getParentRoute: () => WwwRoute,
} as any)

const WwwHelpIndexRoute = WwwHelpIndexImport.update({
  id: '/help/',
  path: '/help/',
  getParentRoute: () => WwwRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppImport
      parentRoute: typeof rootRoute
    }
    '/_www': {
      id: '/_www'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof WwwImport
      parentRoute: typeof rootRoute
    }
    '/_app/home': {
      id: '/_app/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AppHomeImport
      parentRoute: typeof AppImport
    }
    '/_www/404': {
      id: '/_www/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof Www404Import
      parentRoute: typeof WwwImport
    }
    '/_www/create-account': {
      id: '/_www/create-account'
      path: '/create-account'
      fullPath: '/create-account'
      preLoaderRoute: typeof WwwCreateAccountImport
      parentRoute: typeof WwwImport
    }
    '/_www/login': {
      id: '/_www/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof WwwLoginImport
      parentRoute: typeof WwwImport
    }
    '/_www/': {
      id: '/_www/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof WwwIndexImport
      parentRoute: typeof WwwImport
    }
    '/_www/help/': {
      id: '/_www/help/'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof WwwHelpIndexImport
      parentRoute: typeof WwwImport
    }
    '/_www/legal/': {
      id: '/_www/legal/'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof WwwLegalIndexImport
      parentRoute: typeof WwwImport
    }
  }
}

// Create and export the route tree

interface AppRouteChildren {
  AppHomeRoute: typeof AppHomeRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppHomeRoute: AppHomeRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface WwwRouteChildren {
  Www404Route: typeof Www404Route
  WwwCreateAccountRoute: typeof WwwCreateAccountRoute
  WwwLoginRoute: typeof WwwLoginRoute
  WwwIndexRoute: typeof WwwIndexRoute
  WwwHelpIndexRoute: typeof WwwHelpIndexRoute
  WwwLegalIndexRoute: typeof WwwLegalIndexRoute
}

const WwwRouteChildren: WwwRouteChildren = {
  Www404Route: Www404Route,
  WwwCreateAccountRoute: WwwCreateAccountRoute,
  WwwLoginRoute: WwwLoginRoute,
  WwwIndexRoute: WwwIndexRoute,
  WwwHelpIndexRoute: WwwHelpIndexRoute,
  WwwLegalIndexRoute: WwwLegalIndexRoute,
}

const WwwRouteWithChildren = WwwRoute._addFileChildren(WwwRouteChildren)

export interface FileRoutesByFullPath {
  '': typeof WwwRouteWithChildren
  '/home': typeof AppHomeRoute
  '/404': typeof Www404Route
  '/create-account': typeof WwwCreateAccountRoute
  '/login': typeof WwwLoginRoute
  '/': typeof WwwIndexRoute
  '/help': typeof WwwHelpIndexRoute
  '/legal': typeof WwwLegalIndexRoute
}

export interface FileRoutesByTo {
  '': typeof AppRouteWithChildren
  '/home': typeof AppHomeRoute
  '/404': typeof Www404Route
  '/create-account': typeof WwwCreateAccountRoute
  '/login': typeof WwwLoginRoute
  '/': typeof WwwIndexRoute
  '/help': typeof WwwHelpIndexRoute
  '/legal': typeof WwwLegalIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_app': typeof AppRouteWithChildren
  '/_www': typeof WwwRouteWithChildren
  '/_app/home': typeof AppHomeRoute
  '/_www/404': typeof Www404Route
  '/_www/create-account': typeof WwwCreateAccountRoute
  '/_www/login': typeof WwwLoginRoute
  '/_www/': typeof WwwIndexRoute
  '/_www/help/': typeof WwwHelpIndexRoute
  '/_www/legal/': typeof WwwLegalIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/home'
    | '/404'
    | '/create-account'
    | '/login'
    | '/'
    | '/help'
    | '/legal'
  fileRoutesByTo: FileRoutesByTo
  to:
    | ''
    | '/home'
    | '/404'
    | '/create-account'
    | '/login'
    | '/'
    | '/help'
    | '/legal'
  id:
    | '__root__'
    | '/_app'
    | '/_www'
    | '/_app/home'
    | '/_www/404'
    | '/_www/create-account'
    | '/_www/login'
    | '/_www/'
    | '/_www/help/'
    | '/_www/legal/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  WwwRoute: typeof WwwRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  WwwRoute: WwwRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_app",
        "/_www"
      ]
    },
    "/_app": {
      "filePath": "_app.tsx",
      "children": [
        "/_app/home"
      ]
    },
    "/_www": {
      "filePath": "_www.tsx",
      "children": [
        "/_www/404",
        "/_www/create-account",
        "/_www/login",
        "/_www/",
        "/_www/help/",
        "/_www/legal/"
      ]
    },
    "/_app/home": {
      "filePath": "_app/home.tsx",
      "parent": "/_app"
    },
    "/_www/404": {
      "filePath": "_www/404.tsx",
      "parent": "/_www"
    },
    "/_www/create-account": {
      "filePath": "_www/create-account.tsx",
      "parent": "/_www"
    },
    "/_www/login": {
      "filePath": "_www/login.tsx",
      "parent": "/_www"
    },
    "/_www/": {
      "filePath": "_www/index.tsx",
      "parent": "/_www"
    },
    "/_www/help/": {
      "filePath": "_www/help/index.tsx",
      "parent": "/_www"
    },
    "/_www/legal/": {
      "filePath": "_www/legal/index.tsx",
      "parent": "/_www"
    }
  }
}
ROUTE_MANIFEST_END */
