/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WwwRouteImport } from './routes/_www'
import { Route as AppRouteImport } from './routes/_app'
import { Route as WwwIndexRouteImport } from './routes/_www/index'
import { Route as WwwSuperRouteImport } from './routes/_www/super'
import { Route as WwwLoginRouteImport } from './routes/_www/login'
import { Route as WwwForgotPasswordRouteImport } from './routes/_www/forgot-password'
import { Route as WwwErrorRouteImport } from './routes/_www/error'
import { Route as WwwCreateAccountRouteImport } from './routes/_www/create-account'
import { Route as WwwAboutRouteImport } from './routes/_www/about'
import { Route as Www404RouteImport } from './routes/_www/404'
import { Route as AppProfileRouteImport } from './routes/_app/profile'
import { Route as AppOnboardingRouteImport } from './routes/_app/onboarding'
import { Route as AppMeRouteImport } from './routes/_app/me'
import { Route as AppHomeRouteImport } from './routes/_app/home'
import { Route as AppExploreRouteImport } from './routes/_app/explore'
import { Route as AppChar58usernameRouteImport } from './routes/_app/:username'
import { Route as WwwLegalIndexRouteImport } from './routes/_www/legal/index'
import { Route as WwwHelpIndexRouteImport } from './routes/_www/help/index'
import { Route as WwwDocsIndexRouteImport } from './routes/_www/docs/index'
import { Route as AppSettingsIndexRouteImport } from './routes/_app/settings/index'
import { Route as AppOnboardingIndexRouteImport } from './routes/_app/onboarding/index'
import { Route as WwwLegalTermsOfServiceRouteImport } from './routes/_www/legal/terms-of-service'
import { Route as WwwLegalRefundPolicyRouteImport } from './routes/_www/legal/refund-policy'
import { Route as WwwLegalPrivacyPolicyRouteImport } from './routes/_www/legal/privacy-policy'
import { Route as WwwLegalCookiePolicyRouteImport } from './routes/_www/legal/cookie-policy'
import { Route as WwwLegalCompanyRouteImport } from './routes/_www/legal/company'
import { Route as WwwLegalCommunityRulesRouteImport } from './routes/_www/legal/community-rules'
import { Route as WwwHelpSlugRouteImport } from './routes/_www/help/$slug'
import { Route as AppProfileEditRouteImport } from './routes/_app/profile/edit'
import { Route as AppProfileUsernameRouteImport } from './routes/_app/profile/$username'
import { Route as AppOnboardingTodosRouteImport } from './routes/_app/onboarding/todos'
import { Route as AppOnboardingProfileRouteImport } from './routes/_app/onboarding/profile'
import { Route as AppOnboardingGoalsRouteImport } from './routes/_app/onboarding/goals'
import { Route as AppOnboardingCompleteRouteImport } from './routes/_app/onboarding/complete'

const WwwRoute = WwwRouteImport.update({
  id: '/_www',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const WwwIndexRoute = WwwIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WwwRoute,
} as any)
const WwwSuperRoute = WwwSuperRouteImport.update({
  id: '/super',
  path: '/super',
  getParentRoute: () => WwwRoute,
} as any)
const WwwLoginRoute = WwwLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => WwwRoute,
} as any)
const WwwForgotPasswordRoute = WwwForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => WwwRoute,
} as any)
const WwwErrorRoute = WwwErrorRouteImport.update({
  id: '/error',
  path: '/error',
  getParentRoute: () => WwwRoute,
} as any)
const WwwCreateAccountRoute = WwwCreateAccountRouteImport.update({
  id: '/create-account',
  path: '/create-account',
  getParentRoute: () => WwwRoute,
} as any)
const WwwAboutRoute = WwwAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => WwwRoute,
} as any)
const Www404Route = Www404RouteImport.update({
  id: '/404',
  path: '/404',
  getParentRoute: () => WwwRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppOnboardingRoute = AppOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AppRoute,
} as any)
const AppMeRoute = AppMeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => AppRoute,
} as any)
const AppHomeRoute = AppHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AppRoute,
} as any)
const AppExploreRoute = AppExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => AppRoute,
} as any)
const AppChar58usernameRoute = AppChar58usernameRouteImport.update({
  id: '/:username',
  path: '/:username',
  getParentRoute: () => AppRoute,
} as any)
const WwwLegalIndexRoute = WwwLegalIndexRouteImport.update({
  id: '/legal/',
  path: '/legal/',
  getParentRoute: () => WwwRoute,
} as any)
const WwwHelpIndexRoute = WwwHelpIndexRouteImport.update({
  id: '/help/',
  path: '/help/',
  getParentRoute: () => WwwRoute,
} as any)
const WwwDocsIndexRoute = WwwDocsIndexRouteImport.update({
  id: '/docs/',
  path: '/docs/',
  getParentRoute: () => WwwRoute,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AppRoute,
} as any)
const AppOnboardingIndexRoute = AppOnboardingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppOnboardingRoute,
} as any)
const WwwLegalTermsOfServiceRoute = WwwLegalTermsOfServiceRouteImport.update({
  id: '/legal/terms-of-service',
  path: '/legal/terms-of-service',
  getParentRoute: () => WwwRoute,
} as any)
const WwwLegalRefundPolicyRoute = WwwLegalRefundPolicyRouteImport.update({
  id: '/legal/refund-policy',
  path: '/legal/refund-policy',
  getParentRoute: () => WwwRoute,
} as any)
const WwwLegalPrivacyPolicyRoute = WwwLegalPrivacyPolicyRouteImport.update({
  id: '/legal/privacy-policy',
  path: '/legal/privacy-policy',
  getParentRoute: () => WwwRoute,
} as any)
const WwwLegalCookiePolicyRoute = WwwLegalCookiePolicyRouteImport.update({
  id: '/legal/cookie-policy',
  path: '/legal/cookie-policy',
  getParentRoute: () => WwwRoute,
} as any)
const WwwLegalCompanyRoute = WwwLegalCompanyRouteImport.update({
  id: '/legal/company',
  path: '/legal/company',
  getParentRoute: () => WwwRoute,
} as any)
const WwwLegalCommunityRulesRoute = WwwLegalCommunityRulesRouteImport.update({
  id: '/legal/community-rules',
  path: '/legal/community-rules',
  getParentRoute: () => WwwRoute,
} as any)
const WwwHelpSlugRoute = WwwHelpSlugRouteImport.update({
  id: '/help/$slug',
  path: '/help/$slug',
  getParentRoute: () => WwwRoute,
} as any)
const AppProfileEditRoute = AppProfileEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => AppProfileRoute,
} as any)
const AppProfileUsernameRoute = AppProfileUsernameRouteImport.update({
  id: '/$username',
  path: '/$username',
  getParentRoute: () => AppProfileRoute,
} as any)
const AppOnboardingTodosRoute = AppOnboardingTodosRouteImport.update({
  id: '/todos',
  path: '/todos',
  getParentRoute: () => AppOnboardingRoute,
} as any)
const AppOnboardingProfileRoute = AppOnboardingProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppOnboardingRoute,
} as any)
const AppOnboardingGoalsRoute = AppOnboardingGoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => AppOnboardingRoute,
} as any)
const AppOnboardingCompleteRoute = AppOnboardingCompleteRouteImport.update({
  id: '/complete',
  path: '/complete',
  getParentRoute: () => AppOnboardingRoute,
} as any)

export interface FileRoutesByFullPath {
  '/:username': typeof AppChar58usernameRoute
  '/explore': typeof AppExploreRoute
  '/home': typeof AppHomeRoute
  '/me': typeof AppMeRoute
  '/onboarding': typeof AppOnboardingRouteWithChildren
  '/profile': typeof AppProfileRouteWithChildren
  '/404': typeof Www404Route
  '/about': typeof WwwAboutRoute
  '/create-account': typeof WwwCreateAccountRoute
  '/error': typeof WwwErrorRoute
  '/forgot-password': typeof WwwForgotPasswordRoute
  '/login': typeof WwwLoginRoute
  '/super': typeof WwwSuperRoute
  '/': typeof WwwIndexRoute
  '/onboarding/complete': typeof AppOnboardingCompleteRoute
  '/onboarding/goals': typeof AppOnboardingGoalsRoute
  '/onboarding/profile': typeof AppOnboardingProfileRoute
  '/onboarding/todos': typeof AppOnboardingTodosRoute
  '/profile/$username': typeof AppProfileUsernameRoute
  '/profile/edit': typeof AppProfileEditRoute
  '/help/$slug': typeof WwwHelpSlugRoute
  '/legal/community-rules': typeof WwwLegalCommunityRulesRoute
  '/legal/company': typeof WwwLegalCompanyRoute
  '/legal/cookie-policy': typeof WwwLegalCookiePolicyRoute
  '/legal/privacy-policy': typeof WwwLegalPrivacyPolicyRoute
  '/legal/refund-policy': typeof WwwLegalRefundPolicyRoute
  '/legal/terms-of-service': typeof WwwLegalTermsOfServiceRoute
  '/onboarding/': typeof AppOnboardingIndexRoute
  '/settings': typeof AppSettingsIndexRoute
  '/docs': typeof WwwDocsIndexRoute
  '/help': typeof WwwHelpIndexRoute
  '/legal': typeof WwwLegalIndexRoute
}
export interface FileRoutesByTo {
  '/:username': typeof AppChar58usernameRoute
  '/explore': typeof AppExploreRoute
  '/home': typeof AppHomeRoute
  '/me': typeof AppMeRoute
  '/profile': typeof AppProfileRouteWithChildren
  '/404': typeof Www404Route
  '/about': typeof WwwAboutRoute
  '/create-account': typeof WwwCreateAccountRoute
  '/error': typeof WwwErrorRoute
  '/forgot-password': typeof WwwForgotPasswordRoute
  '/login': typeof WwwLoginRoute
  '/super': typeof WwwSuperRoute
  '/': typeof WwwIndexRoute
  '/onboarding/complete': typeof AppOnboardingCompleteRoute
  '/onboarding/goals': typeof AppOnboardingGoalsRoute
  '/onboarding/profile': typeof AppOnboardingProfileRoute
  '/onboarding/todos': typeof AppOnboardingTodosRoute
  '/profile/$username': typeof AppProfileUsernameRoute
  '/profile/edit': typeof AppProfileEditRoute
  '/help/$slug': typeof WwwHelpSlugRoute
  '/legal/community-rules': typeof WwwLegalCommunityRulesRoute
  '/legal/company': typeof WwwLegalCompanyRoute
  '/legal/cookie-policy': typeof WwwLegalCookiePolicyRoute
  '/legal/privacy-policy': typeof WwwLegalPrivacyPolicyRoute
  '/legal/refund-policy': typeof WwwLegalRefundPolicyRoute
  '/legal/terms-of-service': typeof WwwLegalTermsOfServiceRoute
  '/onboarding': typeof AppOnboardingIndexRoute
  '/settings': typeof AppSettingsIndexRoute
  '/docs': typeof WwwDocsIndexRoute
  '/help': typeof WwwHelpIndexRoute
  '/legal': typeof WwwLegalIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_www': typeof WwwRouteWithChildren
  '/_app/:username': typeof AppChar58usernameRoute
  '/_app/explore': typeof AppExploreRoute
  '/_app/home': typeof AppHomeRoute
  '/_app/me': typeof AppMeRoute
  '/_app/onboarding': typeof AppOnboardingRouteWithChildren
  '/_app/profile': typeof AppProfileRouteWithChildren
  '/_www/404': typeof Www404Route
  '/_www/about': typeof WwwAboutRoute
  '/_www/create-account': typeof WwwCreateAccountRoute
  '/_www/error': typeof WwwErrorRoute
  '/_www/forgot-password': typeof WwwForgotPasswordRoute
  '/_www/login': typeof WwwLoginRoute
  '/_www/super': typeof WwwSuperRoute
  '/_www/': typeof WwwIndexRoute
  '/_app/onboarding/complete': typeof AppOnboardingCompleteRoute
  '/_app/onboarding/goals': typeof AppOnboardingGoalsRoute
  '/_app/onboarding/profile': typeof AppOnboardingProfileRoute
  '/_app/onboarding/todos': typeof AppOnboardingTodosRoute
  '/_app/profile/$username': typeof AppProfileUsernameRoute
  '/_app/profile/edit': typeof AppProfileEditRoute
  '/_www/help/$slug': typeof WwwHelpSlugRoute
  '/_www/legal/community-rules': typeof WwwLegalCommunityRulesRoute
  '/_www/legal/company': typeof WwwLegalCompanyRoute
  '/_www/legal/cookie-policy': typeof WwwLegalCookiePolicyRoute
  '/_www/legal/privacy-policy': typeof WwwLegalPrivacyPolicyRoute
  '/_www/legal/refund-policy': typeof WwwLegalRefundPolicyRoute
  '/_www/legal/terms-of-service': typeof WwwLegalTermsOfServiceRoute
  '/_app/onboarding/': typeof AppOnboardingIndexRoute
  '/_app/settings/': typeof AppSettingsIndexRoute
  '/_www/docs/': typeof WwwDocsIndexRoute
  '/_www/help/': typeof WwwHelpIndexRoute
  '/_www/legal/': typeof WwwLegalIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/:username'
    | '/explore'
    | '/home'
    | '/me'
    | '/onboarding'
    | '/profile'
    | '/404'
    | '/about'
    | '/create-account'
    | '/error'
    | '/forgot-password'
    | '/login'
    | '/super'
    | '/'
    | '/onboarding/complete'
    | '/onboarding/goals'
    | '/onboarding/profile'
    | '/onboarding/todos'
    | '/profile/$username'
    | '/profile/edit'
    | '/help/$slug'
    | '/legal/community-rules'
    | '/legal/company'
    | '/legal/cookie-policy'
    | '/legal/privacy-policy'
    | '/legal/refund-policy'
    | '/legal/terms-of-service'
    | '/onboarding/'
    | '/settings'
    | '/docs'
    | '/help'
    | '/legal'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/:username'
    | '/explore'
    | '/home'
    | '/me'
    | '/profile'
    | '/404'
    | '/about'
    | '/create-account'
    | '/error'
    | '/forgot-password'
    | '/login'
    | '/super'
    | '/'
    | '/onboarding/complete'
    | '/onboarding/goals'
    | '/onboarding/profile'
    | '/onboarding/todos'
    | '/profile/$username'
    | '/profile/edit'
    | '/help/$slug'
    | '/legal/community-rules'
    | '/legal/company'
    | '/legal/cookie-policy'
    | '/legal/privacy-policy'
    | '/legal/refund-policy'
    | '/legal/terms-of-service'
    | '/onboarding'
    | '/settings'
    | '/docs'
    | '/help'
    | '/legal'
  id:
    | '__root__'
    | '/_app'
    | '/_www'
    | '/_app/:username'
    | '/_app/explore'
    | '/_app/home'
    | '/_app/me'
    | '/_app/onboarding'
    | '/_app/profile'
    | '/_www/404'
    | '/_www/about'
    | '/_www/create-account'
    | '/_www/error'
    | '/_www/forgot-password'
    | '/_www/login'
    | '/_www/super'
    | '/_www/'
    | '/_app/onboarding/complete'
    | '/_app/onboarding/goals'
    | '/_app/onboarding/profile'
    | '/_app/onboarding/todos'
    | '/_app/profile/$username'
    | '/_app/profile/edit'
    | '/_www/help/$slug'
    | '/_www/legal/community-rules'
    | '/_www/legal/company'
    | '/_www/legal/cookie-policy'
    | '/_www/legal/privacy-policy'
    | '/_www/legal/refund-policy'
    | '/_www/legal/terms-of-service'
    | '/_app/onboarding/'
    | '/_app/settings/'
    | '/_www/docs/'
    | '/_www/help/'
    | '/_www/legal/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  WwwRoute: typeof WwwRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_www': {
      id: '/_www'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof WwwRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_www/': {
      id: '/_www/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof WwwIndexRouteImport
      parentRoute: typeof WwwRoute
    }
    '/_www/super': {
      id: '/_www/super'
      path: '/super'
      fullPath: '/super'
      preLoaderRoute: typeof WwwSuperRouteImport
      parentRoute: typeof WwwRoute
    }
    '/_www/login': {
      id: '/_www/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof WwwLoginRouteImport
      parentRoute: typeof WwwRoute
    }
    '/_www/forgot-password': {
      id: '/_www/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof WwwForgotPasswordRouteImport
      parentRoute: typeof WwwRoute
    }
    '/_www/error': {
      id: '/_www/error'
      path: '/error'
      fullPath: '/error'
      preLoaderRoute: typeof WwwErrorRouteImport
      parentRoute: typeof WwwRoute
    }
    '/_www/create-account': {
      id: '/_www/create-account'
      path: '/create-account'
      fullPath: '/create-account'
      preLoaderRoute: typeof WwwCreateAccountRouteImport
      parentRoute: typeof WwwRoute
    }
    '/_www/about': {
      id: '/_www/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof WwwAboutRouteImport
      parentRoute: typeof WwwRoute
    }
    '/_www/404': {
      id: '/_www/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof Www404RouteImport
      parentRoute: typeof WwwRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/onboarding': {
      id: '/_app/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AppOnboardingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/me': {
      id: '/_app/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof AppMeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/home': {
      id: '/_app/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AppHomeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/explore': {
      id: '/_app/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof AppExploreRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/:username': {
      id: '/_app/:username'
      path: '/:username'
      fullPath: '/:username'
      preLoaderRoute: typeof AppChar58usernameRouteImport
      parentRoute: typeof AppRoute
    }
    '/_www/legal/': {
      id: '/_www/legal/'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof WwwLegalIndexRouteImport
      parentRoute: typeof WwwRoute
    }
    '/_www/help/': {
      id: '/_www/help/'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof WwwHelpIndexRouteImport
      parentRoute: typeof WwwRoute
    }
    '/_www/docs/': {
      id: '/_www/docs/'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof WwwDocsIndexRouteImport
      parentRoute: typeof WwwRoute
    }
    '/_app/settings/': {
      id: '/_app/settings/'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/onboarding/': {
      id: '/_app/onboarding/'
      path: '/'
      fullPath: '/onboarding/'
      preLoaderRoute: typeof AppOnboardingIndexRouteImport
      parentRoute: typeof AppOnboardingRoute
    }
    '/_www/legal/terms-of-service': {
      id: '/_www/legal/terms-of-service'
      path: '/legal/terms-of-service'
      fullPath: '/legal/terms-of-service'
      preLoaderRoute: typeof WwwLegalTermsOfServiceRouteImport
      parentRoute: typeof WwwRoute
    }
    '/_www/legal/refund-policy': {
      id: '/_www/legal/refund-policy'
      path: '/legal/refund-policy'
      fullPath: '/legal/refund-policy'
      preLoaderRoute: typeof WwwLegalRefundPolicyRouteImport
      parentRoute: typeof WwwRoute
    }
    '/_www/legal/privacy-policy': {
      id: '/_www/legal/privacy-policy'
      path: '/legal/privacy-policy'
      fullPath: '/legal/privacy-policy'
      preLoaderRoute: typeof WwwLegalPrivacyPolicyRouteImport
      parentRoute: typeof WwwRoute
    }
    '/_www/legal/cookie-policy': {
      id: '/_www/legal/cookie-policy'
      path: '/legal/cookie-policy'
      fullPath: '/legal/cookie-policy'
      preLoaderRoute: typeof WwwLegalCookiePolicyRouteImport
      parentRoute: typeof WwwRoute
    }
    '/_www/legal/company': {
      id: '/_www/legal/company'
      path: '/legal/company'
      fullPath: '/legal/company'
      preLoaderRoute: typeof WwwLegalCompanyRouteImport
      parentRoute: typeof WwwRoute
    }
    '/_www/legal/community-rules': {
      id: '/_www/legal/community-rules'
      path: '/legal/community-rules'
      fullPath: '/legal/community-rules'
      preLoaderRoute: typeof WwwLegalCommunityRulesRouteImport
      parentRoute: typeof WwwRoute
    }
    '/_www/help/$slug': {
      id: '/_www/help/$slug'
      path: '/help/$slug'
      fullPath: '/help/$slug'
      preLoaderRoute: typeof WwwHelpSlugRouteImport
      parentRoute: typeof WwwRoute
    }
    '/_app/profile/edit': {
      id: '/_app/profile/edit'
      path: '/edit'
      fullPath: '/profile/edit'
      preLoaderRoute: typeof AppProfileEditRouteImport
      parentRoute: typeof AppProfileRoute
    }
    '/_app/profile/$username': {
      id: '/_app/profile/$username'
      path: '/$username'
      fullPath: '/profile/$username'
      preLoaderRoute: typeof AppProfileUsernameRouteImport
      parentRoute: typeof AppProfileRoute
    }
    '/_app/onboarding/todos': {
      id: '/_app/onboarding/todos'
      path: '/todos'
      fullPath: '/onboarding/todos'
      preLoaderRoute: typeof AppOnboardingTodosRouteImport
      parentRoute: typeof AppOnboardingRoute
    }
    '/_app/onboarding/profile': {
      id: '/_app/onboarding/profile'
      path: '/profile'
      fullPath: '/onboarding/profile'
      preLoaderRoute: typeof AppOnboardingProfileRouteImport
      parentRoute: typeof AppOnboardingRoute
    }
    '/_app/onboarding/goals': {
      id: '/_app/onboarding/goals'
      path: '/goals'
      fullPath: '/onboarding/goals'
      preLoaderRoute: typeof AppOnboardingGoalsRouteImport
      parentRoute: typeof AppOnboardingRoute
    }
    '/_app/onboarding/complete': {
      id: '/_app/onboarding/complete'
      path: '/complete'
      fullPath: '/onboarding/complete'
      preLoaderRoute: typeof AppOnboardingCompleteRouteImport
      parentRoute: typeof AppOnboardingRoute
    }
  }
}

interface AppOnboardingRouteChildren {
  AppOnboardingCompleteRoute: typeof AppOnboardingCompleteRoute
  AppOnboardingGoalsRoute: typeof AppOnboardingGoalsRoute
  AppOnboardingProfileRoute: typeof AppOnboardingProfileRoute
  AppOnboardingTodosRoute: typeof AppOnboardingTodosRoute
  AppOnboardingIndexRoute: typeof AppOnboardingIndexRoute
}

const AppOnboardingRouteChildren: AppOnboardingRouteChildren = {
  AppOnboardingCompleteRoute: AppOnboardingCompleteRoute,
  AppOnboardingGoalsRoute: AppOnboardingGoalsRoute,
  AppOnboardingProfileRoute: AppOnboardingProfileRoute,
  AppOnboardingTodosRoute: AppOnboardingTodosRoute,
  AppOnboardingIndexRoute: AppOnboardingIndexRoute,
}

const AppOnboardingRouteWithChildren = AppOnboardingRoute._addFileChildren(
  AppOnboardingRouteChildren,
)

interface AppProfileRouteChildren {
  AppProfileUsernameRoute: typeof AppProfileUsernameRoute
  AppProfileEditRoute: typeof AppProfileEditRoute
}

const AppProfileRouteChildren: AppProfileRouteChildren = {
  AppProfileUsernameRoute: AppProfileUsernameRoute,
  AppProfileEditRoute: AppProfileEditRoute,
}

const AppProfileRouteWithChildren = AppProfileRoute._addFileChildren(
  AppProfileRouteChildren,
)

interface AppRouteChildren {
  AppChar58usernameRoute: typeof AppChar58usernameRoute
  AppExploreRoute: typeof AppExploreRoute
  AppHomeRoute: typeof AppHomeRoute
  AppMeRoute: typeof AppMeRoute
  AppOnboardingRoute: typeof AppOnboardingRouteWithChildren
  AppProfileRoute: typeof AppProfileRouteWithChildren
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppChar58usernameRoute: AppChar58usernameRoute,
  AppExploreRoute: AppExploreRoute,
  AppHomeRoute: AppHomeRoute,
  AppMeRoute: AppMeRoute,
  AppOnboardingRoute: AppOnboardingRouteWithChildren,
  AppProfileRoute: AppProfileRouteWithChildren,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface WwwRouteChildren {
  Www404Route: typeof Www404Route
  WwwAboutRoute: typeof WwwAboutRoute
  WwwCreateAccountRoute: typeof WwwCreateAccountRoute
  WwwErrorRoute: typeof WwwErrorRoute
  WwwForgotPasswordRoute: typeof WwwForgotPasswordRoute
  WwwLoginRoute: typeof WwwLoginRoute
  WwwSuperRoute: typeof WwwSuperRoute
  WwwIndexRoute: typeof WwwIndexRoute
  WwwHelpSlugRoute: typeof WwwHelpSlugRoute
  WwwLegalCommunityRulesRoute: typeof WwwLegalCommunityRulesRoute
  WwwLegalCompanyRoute: typeof WwwLegalCompanyRoute
  WwwLegalCookiePolicyRoute: typeof WwwLegalCookiePolicyRoute
  WwwLegalPrivacyPolicyRoute: typeof WwwLegalPrivacyPolicyRoute
  WwwLegalRefundPolicyRoute: typeof WwwLegalRefundPolicyRoute
  WwwLegalTermsOfServiceRoute: typeof WwwLegalTermsOfServiceRoute
  WwwDocsIndexRoute: typeof WwwDocsIndexRoute
  WwwHelpIndexRoute: typeof WwwHelpIndexRoute
  WwwLegalIndexRoute: typeof WwwLegalIndexRoute
}

const WwwRouteChildren: WwwRouteChildren = {
  Www404Route: Www404Route,
  WwwAboutRoute: WwwAboutRoute,
  WwwCreateAccountRoute: WwwCreateAccountRoute,
  WwwErrorRoute: WwwErrorRoute,
  WwwForgotPasswordRoute: WwwForgotPasswordRoute,
  WwwLoginRoute: WwwLoginRoute,
  WwwSuperRoute: WwwSuperRoute,
  WwwIndexRoute: WwwIndexRoute,
  WwwHelpSlugRoute: WwwHelpSlugRoute,
  WwwLegalCommunityRulesRoute: WwwLegalCommunityRulesRoute,
  WwwLegalCompanyRoute: WwwLegalCompanyRoute,
  WwwLegalCookiePolicyRoute: WwwLegalCookiePolicyRoute,
  WwwLegalPrivacyPolicyRoute: WwwLegalPrivacyPolicyRoute,
  WwwLegalRefundPolicyRoute: WwwLegalRefundPolicyRoute,
  WwwLegalTermsOfServiceRoute: WwwLegalTermsOfServiceRoute,
  WwwDocsIndexRoute: WwwDocsIndexRoute,
  WwwHelpIndexRoute: WwwHelpIndexRoute,
  WwwLegalIndexRoute: WwwLegalIndexRoute,
}

const WwwRouteWithChildren = WwwRoute._addFileChildren(WwwRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  WwwRoute: WwwRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
